# Generated by Django 5.0.6 on 2024-09-04 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='adminchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('small_title', models.CharField(max_length=50)),
                ('small_content', models.CharField(max_length=50)),
                ('job_images', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('principal_name', models.CharField(max_length=255, null=True)),
                ('principal_number', models.CharField(max_length=50, null=True)),
                ('principal_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('placement_officer_name', models.CharField(max_length=255, null=True)),
                ('placement_officer_num', models.CharField(max_length=50, null=True)),
                ('placement_officer_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('stream', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('contact_type', models.CharField(max_length=50)),
                ('number_of_dept', models.PositiveIntegerField()),
                ('ug_students', models.CharField(max_length=50)),
                ('pg_students', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=100)),
                ('passed_out', models.CharField(max_length=4)),
                ('address', models.TextField()),
                ('country_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('student_ug_pg', models.CharField(max_length=50)),
                ('student_stream', models.CharField(max_length=50)),
                ('student_dept', models.CharField(max_length=50)),
                ('student_sem', models.PositiveIntegerField()),
                ('student_10_mark', models.PositiveIntegerField()),
                ('student_12_mark', models.PositiveIntegerField()),
                ('student_aadhar_num', models.CharField(max_length=50)),
                ('student_pan_num', models.CharField(max_length=50)),
                ('student_cgpa', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_phone_num', models.CharField(max_length=50, unique=True)),
                ('student_alter_num', models.CharField(blank=True, max_length=50)),
                ('student_address', models.CharField(max_length=250)),
                ('student_resume', models.FileField(upload_to='resumes/')),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
