# Generated by Django 5.0.6 on 2024-09-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_mr_mrs', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('house_no', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('alt_email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('alt_mobile', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTable',
            fields=[
                ('it_bps', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('aadhar', models.CharField(max_length=12)),
                ('firstname', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='admin_user_login',
        ),
        migrations.DeleteModel(
            name='adminchanges',
        ),
        migrations.DeleteModel(
            name='CollegeRegistration',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='primary_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobfairapp.primarytable'),
        ),
    ]
