# Generated by Django 5.0.6 on 2024-09-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairapp', '0003_academicdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration_start', models.DateField()),
                ('course_duration_end', models.DateField()),
                ('course_type', models.CharField(max_length=50)),
                ('university_college_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('grading_system', models.CharField(max_length=50)),
                ('primary_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobfairapp.primarytable')),
            ],
        ),
    ]
