# Generated by Django 5.0.6 on 2024-09-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairapp', '0006_xthdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_other_course', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('duration_start', models.DateField()),
                ('duration_end', models.DateField()),
                ('course_type', models.CharField(max_length=50)),
                ('grading_system', models.CharField(max_length=50)),
                ('primary_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobfairapp.primarytable')),
            ],
        ),
    ]
