# Generated by Django 5.0.6 on 2024-09-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairapp', '0007_otherqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('employee_type', models.CharField(max_length=100)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primary_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobfairapp.primarytable')),
            ],
        ),
    ]
