# Generated by Django 5.0.6 on 2024-09-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairapp', '0010_otherdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('cv', models.FileField(upload_to='cvs/')),
                ('primary_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobfairapp.primarytable')),
            ],
        ),
    ]
