# Generated by Django 5.0.6 on 2024-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairapp', '0011_photocv'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='state',
            field=models.CharField(default=18, max_length=50),
            preserve_default=False,
        ),
    ]
